# ----------------- Mi lista de aliases para mi bash ----------------
alias dn='dateScript -dir'
alias rj='reloj.sh'
alias pk='priska.py'
alias sp='speedtest'
alias nv='nvim'
alias python='python3'
alias py='python'
alias newP='newPythonFile.sh'
alias exa='exa --icons'
alias wk='i3-msg workspace'
