# Inserts a blank line between shell prompts
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
symbol = "   "
truncation_length = 8
truncation_symbol = ""

[git_commit]
commit_hash_length = 4
tag_symbol = "🔖 "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_metrics]
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
conflicted = "🏳"
ahead = "🏎💨"
behind = "😰"
diverged = "😵"
up_to_date = "[✓](bold green)"
untracked = "🤷‍"
stashed = "📦"
modified = "📝"
staged = '[++\($count\)](green)'
renamed = "👅"
deleted = "🗑"

[directory]
truncate_to_repo = false
truncation_length = 8
truncation_symbol = "…/"

[hostname]
ssh_only = true
format =  "on [$hostname](bold red) "
trim_at = ".companyname.com"
disabled = false

[memory_usage]
disabled = true 
threshold = -1
symbol = " "
style = "bold dimmed green"

[python]
symbol = "   "
pyenv_version_name = true
python_binary = ["./venv/bin/python", "python", "python3", "python2"]

[time]
disabled = false
format = '🕜[\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "-5"
time_range = "-"
